app = 'test-fly-a2kung'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false  # ✅ ما تقفلش التطبيق تلقائي
  auto_start_machines = true
  min_machines_running = 1    # ✅ خلي دايمًا فيه instance شغالة
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[checks]
  [checks.healthcheck]
    type = "http"
    interval = "15s"
    timeout = "2s"
    method = "get"
    path = "/health"
    port = 8080
